apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: keycloakx
    repo: https://codecentric.github.io/helm-charts
    version: 7.1.8
    releaseName: keycloak
    namespace: keycloak
    valuesFile: values.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: keycloak-realm
    files:
      - realm.json
    options:
      labels:
        app.kubernetes.io/name: keycloak

resources:
  - postgresql.yaml
