keycloak:
  auth:
    adminUser: admin
    # In production, use External Secrets to populate this
    adminPassword: admin
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: keycloak.local
    pathType: Prefix
    annotations:
      nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
  production: false # For local kind cluster testing
  proxy: edge
  
  extraEnvVars:
    - name: KEYCLOAK_EXTRA_ARGS
      value: "--import-realm"

  extraVolumes:
    - name: keycloak-realm
      configMap:
        name: keycloak-realm

  extraVolumeMounts:
    - name: keycloak-realm
      mountPath: "/opt/bitnami/keycloak/data/import"
      readOnly: true

  postgresql:
    auth:
      username: bn_keycloak
      password: "postgres-password"
      database: bitnami_keycloak
    primary:
      persistence:
        enabled: false # Empheral local storage
