# Run Loki in single binary mode for local starter kit testing
deploymentMode: SingleBinary
loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
singleBinary:
  replicas: 1
read:
  replicas: 0
write:
  replicas: 0

# Disable Helm test pods which often use 'latest' tags
test:
  enabled: false
