apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # In a real environment, we would point to the upstream manifests here too
  # github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v2.10.1
  # But since hack/setup.sh installs it, we just patch the existing ConfigMaps

patches:
  - path: argocd-cm-patch.yaml
  - path: argocd-rbac-cm-patch.yaml
