apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-xapp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  project: platform
  source:
    repoURL: 'https://github.com/kwong/perpetual-sandbox.git'
    targetRevision: HEAD
    path: platform/crossplane/apis/xapp
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
