apiVersion: v2
name: platform-otel-collector
description: A Helm chart for deploying Otel Collector customized for the IDP Starter Kit
type: application
version: 0.1.0
appVersion: "0.96.0"

dependencies:
  - name: opentelemetry-collector
    version: 0.85.0
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
