# argocd environment-specific Helm value overrides for dev.
# These patches are applied on top of components/argocd/base/values.yaml.
# See https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/ for syntax.
